services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: usdewatcher
      POSTGRES_USER: usdewatcher
      POSTGRES_PASSWORD: usdewatcher
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      USDEWATCHER_DATABASE_DSN: postgres://usdewatcher:usdewatcher@db:5432/usdewatcher?sslmode=disable
      USDEWATCHER_ETHEREUM_RPC_URL: https://mainnet.infura.io/v3/your-key
    depends_on:
      - db
    command:
      - run
      - --config
      - /app/config.yaml

volumes:
  pgdata:
