// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Alert struct {
	ID           int64              `json:"id"`
	SampleTs     pgtype.Timestamptz `json:"sample_ts"`
	DeviationPct decimal.Decimal    `json:"deviation_pct"`
	ThresholdPct decimal.Decimal    `json:"threshold_pct"`
	Direction    string             `json:"direction"`
	Channels     []string           `json:"channels"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type RateSample struct {
	BucketTs             pgtype.Timestamptz `json:"bucket_ts"`
	OfficialSusdePerUsde decimal.Decimal    `json:"official_susde_per_usde"`
	MarketSusdePerUsde   decimal.Decimal    `json:"market_susde_per_usde"`
	DeviationPct         decimal.Decimal    `json:"deviation_pct"`
	NotionalUsde         decimal.Decimal    `json:"notional_usde"`
	CowQuality           string             `json:"cow_quality"`
	CowQuote             []byte             `json:"cow_quote"`
	BlockNumber          pgtype.Int8        `json:"block_number"`
	Status               string             `json:"status"`
	Error                pgtype.Text        `json:"error"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}
